FROM node:19

WORKDIR /app

ARG VITE_API_BASE_URL
ARG VITE_MAPBOX_ACCESS_TOKEN
ARG GTM_ID

RUN apt update -y && apt upgrade -y
RUN apt install -y nasm
RUN corepack enable && corepack prepare pnpm@latest --activate

CMD ["pnpm", "run", "dev:vite"]